package company.project.main.small.common

import com.google.firebase.auth.FirebaseAuth
import com.google.firebase.auth.FirebaseAuthException
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import org.springframework.test.context.ContextConfiguration
import company.project.infra.config.FirebaseConfig
import company.project.lib.common.objects.Profiles

@ContextConfiguration(classes = [FirebaseConfig::class])
@ActiveProfiles(Profiles.TEST)
@SpringBootTest
class CommonComponentSpec() {
	@Autowired
	private lateinit var firebaseAuth: FirebaseAuth

	@Test
	fun `firebase config 인증 확인`() {
		Assertions.assertThrows(FirebaseAuthException::class.java) {
			firebaseAuth.verifyIdToken(
				"eyJhbGciOiJSUzI1NiIsImtpZCI6ImQxNjg5NDE1ZWMyM2EzMzdlMmJiYWE1ZTNlNjhiNjZkYzk5MzY4ODQiLCJ0eXAiOiJKV1QifQ.eyJuYW1lIjoi6rmA64-Z7ZiEKEtpbSBEb25nIEh5dW4pIiwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0lzcElUWHRqdEx4WHF1RGVTNHBORDFJaExpa3FjNEJVbVBFSGJUWWVMZj1zOTYtYyIsImlzcyI6Imh0dHBzOi8vc2VjdXJldG9rZW4uZ29vZ2xlLmNvbS9wcm9qZi04MDY4YiIsImF1ZCI6InByb2pmLTgwNjhiIiwiYXV0aF90aW1lIjoxNzA0NjY5Nzk3LCJ1c2VyX2lkIjoib0xKWVBsSG5lM1BlUE9raURzVk9RaXhzNmJxMiIsInN1YiI6Im9MSllQbEhuZTNQZVBPa2lEc1ZPUWl4czZicTIiLCJpYXQiOjE3MDQ3ODE1MTAsImV4cCI6MTcwNDc4NTExMCwiZW1haWwiOiJrZGhAdGVhbXNub3diYWxsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmaXJlYmFzZSI6eyJpZGVudGl0aWVzIjp7Imdvb2dsZS5jb20iOlsiMTE3MzY0NDk1MzU4NjM1NTE1NTA1Il0sImVtYWlsIjpbImtkaEB0ZWFtc25vd2JhbGwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoiZ29vZ2xlLmNvbSJ9fQ.PvWn5rR1jFZzO74GOdWDgWO0lKU_Bf7L0tZVFzVGVpqzvb1ZgAp4Rv_BcX5mJg2RgL9xLU_kOI1sTG2m8qToWjvjWIrmrFNb5rvbkXypjodjcyHjonz2W4GcBADBoxRL504cUokkcIg3K2f9f2yAhtI1utaJC_0i_mAypex934T0NzdEjulamhiLONgI2kzkU1xfyQioR-7gz1CURGyXkWb-SQu13fhg2onGz7Fm38uRACKjJtAsD_CESwmtoqnq84wca6wxViojMjfes-he8LiWomOo11uqujpQX18K-RZdCS6JhhtKcO-Wvb7p6vzemreh5OVklRXS8j7bbO71RA",
			)
		}
	}
}
